# Generated by Django 4.0.8 on 2022-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('idnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('idphoto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('nssfphoto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('nhifphoto', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
