# Generated by Django 4.0.8 on 2022-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
