# Generated by Django 4.0.8 on 2022-11-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0002_alter_employee_options_employee_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
