# Generated by Django 4.0.8 on 2022-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0003_employee_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
