# Generated by Django 4.1.3 on 2022-11-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0005_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idphoto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nhifphoto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssfphoto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.CreateModel(
            name='Sallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('nhif', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('nssf', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('netSalary', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PanaceaApp.employee')),
            ],
        ),
    ]
