# Generated by Django 4.1.3 on 2022-11-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0009_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sallary',
            name='netSalary',
        ),
    ]
