# Generated by Django 4.0.8 on 2022-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanaceaApp', '0010_remove_sallary_netsalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sallary',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='sallary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sallary',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
